// vocabulary.js

let vocabulary = [
    // Top 100 most frequent words
    { spanish: "el", english: "the", german: "der/die/das" },
    { spanish: "de", english: "of/from", german: "von/aus" },
    { spanish: "que", english: "that/which", german: "dass/welche" },
    { spanish: "y", english: "and", german: "und" },
    { spanish: "a", english: "to", german: "zu" },
    { spanish: "en", english: "in/on", german: "in/auf" },
    { spanish: "un", english: "a/an", german: "ein/eine" },
    { spanish: "es", english: "is", german: "ist" },
    { spanish: "se", english: "oneself", german: "sich" },
    { spanish: "no", english: "no/not", german: "nein/nicht" },
    { spanish: "te", english: "you", german: "dich" },
    { spanish: "lo", english: "it/him", german: "es/ihn" },
    { spanish: "le", english: "to him/her", german: "ihm/ihr" },
    { spanish: "da", english: "gives", german: "gibt" },
    { spanish: "su", english: "his/her/your", german: "sein/ihr" },
    { spanish: "por", english: "for/by", german: "für/durch" },
    { spanish: "son", english: "are", german: "sind" },
    { spanish: "con", english: "with", german: "mit" },
    { spanish: "para", english: "for", german: "für" },
    { spanish: "al", english: "to the", german: "zum/zur" },
    { spanish: "la", english: "the", german: "die" },
    { spanish: "una", english: "a/an", german: "eine" },
    { spanish: "ser", english: "to be", german: "sein" },
    { spanish: "estar", english: "to be", german: "sein/sich befinden" },
    { spanish: "tener", english: "to have", german: "haben" },
    { spanish: "hacer", english: "to do/make", german: "machen/tun" },
    { spanish: "todo", english: "all/everything", german: "alles" },
    { spanish: "más", english: "more", german: "mehr" },
    { spanish: "como", english: "like/how", german: "wie" },
    { spanish: "pero", english: "but", german: "aber" },
    { spanish: "sus", english: "their", german: "ihre" },
    { spanish: "me", english: "me", german: "mich/mir" },
    { spanish: "ya", english: "already", german: "schon" },
    { spanish: "muy", english: "very", german: "sehr" },
    { spanish: "sin", english: "without", german: "ohne" },
    { spanish: "sobre", english: "about/on", german: "über/auf" },
    { spanish: "también", english: "also", german: "auch" },
    { spanish: "hasta", english: "until", german: "bis" },
    { spanish: "hay", english: "there is/are", german: "es gibt" },
    { spanish: "donde", english: "where", german: "wo" },
    { spanish: "han", english: "have", german: "haben" },
    { spanish: "quien", english: "who", german: "wer" },
    { spanish: "está", english: "is", german: "ist" },
    { spanish: "fue", english: "was", german: "war" },
    { spanish: "tiempo", english: "time", german: "Zeit" },
    { spanish: "cada", english: "each", german: "jeder" },
    { spanish: "país", english: "country", german: "Land" },
    { spanish: "vida", english: "life", german: "Leben" },
    { spanish: "trabajo", english: "work", german: "Arbeit" },
    { spanish: "día", english: "day", german: "Tag" },
    { spanish: "agua", english: "water", german: "Wasser" },
    { spanish: "parte", english: "part", german: "Teil" },
    { spanish: "casa", english: "house", german: "Haus" },
    { spanish: "caso", english: "case", german: "Fall" },
    { spanish: "lugar", english: "place", german: "Ort" },
    { spanish: "año", english: "year", german: "Jahr" },
    { spanish: "estado", english: "state", german: "Staat/Zustand" },
    { spanish: "forma", english: "form/way", german: "Form/Art" },
    { spanish: "manera", english: "way", german: "Art/Weise" },
    { spanish: "poder", english: "power/can", german: "Macht/können" },
    { spanish: "decir", english: "to say", german: "sagen" },
    { spanish: "tanto", english: "so much", german: "so viel" },
    { spanish: "momento", english: "moment", german: "Moment" },
    { spanish: "mano", english: "hand", german: "Hand" },
    { spanish: "encuentra", english: "finds", german: "findet" },
    { spanish: "cabeza", english: "head", german: "Kopf" },
    { spanish: "mundo", english: "world", german: "Welt" },
    { spanish: "hora", english: "hour", german: "Stunde" },
    { spanish: "hombre", english: "man", german: "Mann" },
    { spanish: "mujer", english: "woman", german: "Frau" },
    { spanish: "niño", english: "child/boy", german: "Kind/Junge" },
    { spanish: "niña", english: "girl", german: "Mädchen" },
    { spanish: "ojos", english: "eyes", german: "Augen" },
    { spanish: "vez", english: "time/turn", german: "Mal" },
    { spanish: "gobierno", english: "government", german: "Regierung" },
    { spanish: "empresa", english: "company", german: "Unternehmen" },
    { spanish: "grupo", english: "group", german: "Gruppe" },
    { spanish: "dinero", english: "money", german: "Geld" },
    { spanish: "persona", english: "person", german: "Person" },
    { spanish: "nombre", english: "name", german: "Name" },
    { spanish: "número", english: "number", german: "Nummer" },
    { spanish: "familia", english: "family", german: "Familie" },
    { spanish: "ciudad", english: "city", german: "Stadt" },
    { spanish: "problema", english: "problem", german: "Problem" },
    { spanish: "proyecto", english: "project", german: "Projekt" },
    { spanish: "información", english: "information", german: "Information" },
    { spanish: "sistema", english: "system", german: "System" },
    { spanish: "servicio", english: "service", german: "Service" },
    { spanish: "madre", english: "mother", german: "Mutter" },
    { spanish: "padre", english: "father", german: "Vater" },
    { spanish: "hijo", english: "son", german: "Sohn" },
    { spanish: "hija", english: "daughter", german: "Tochter" },
    { spanish: "hermano", english: "brother", german: "Bruder" },
    { spanish: "hermana", english: "sister", german: "Schwester" },
    { spanish: "amigo", english: "friend", german: "Freund" },
    { spanish: "amor", english: "love", german: "Liebe" },
    { spanish: "mejor", english: "better/best", german: "besser/beste" },
    { spanish: "grande", english: "big", german: "groß" },
    { spanish: "pequeño", english: "small", german: "klein" },
    { spanish: "nuevo", english: "new", german: "neu" },
    { spanish: "viejo", english: "old", german: "alt" },
    { spanish: "bueno", english: "good", german: "gut" },
    { spanish: "malo", english: "bad", german: "schlecht" },
    { spanish: "primer", english: "first", german: "erste" },
    { spanish: "último", english: "last", german: "letzte" },
    { spanish: "mismo", english: "same", german: "gleich" },
    { spanish: "otro", english: "other", german: "andere" },
    { spanish: "poco", english: "little", german: "wenig" },
    { spanish: "mucho", english: "much/many", german: "viel" },
    { spanish: "todos", english: "all/everyone", german: "alle" },
    { spanish: "algunas", english: "some", german: "einige" },
    { spanish: "varios", english: "several", german: "mehrere" },
    // Common verbs
    { spanish: "ir", english: "to go", german: "gehen" },
    { spanish: "venir", english: "to come", german: "kommen" },
    { spanish: "ver", english: "to see", german: "sehen" },
    { spanish: "dar", english: "to give", german: "geben" },
    { spanish: "saber", english: "to know", german: "wissen" },
    { spanish: "querer", english: "to want", german: "wollen" },
    { spanish: "llegar", english: "to arrive", german: "ankommen" },
    { spanish: "pasar", english: "to pass", german: "vorbeigehen" },
    { spanish: "deber", english: "should/must", german: "sollen/müssen" },
    { spanish: "poner", english: "to put", german: "setzen/stellen" },
    { spanish: "parecer", english: "to seem", german: "scheinen" },
    { spanish: "quedar", english: "to remain", german: "bleiben" },
    { spanish: "creer", english: "to believe", german: "glauben" },
    { spanish: "hablar", english: "to speak", german: "sprechen" },
    { spanish: "llevar", english: "to carry", german: "tragen" },
    { spanish: "dejar", english: "to leave", german: "verlassen" },
    { spanish: "seguir", english: "to follow", german: "folgen" },
    { spanish: "encontrar", english: "to find", german: "finden" },
    { spanish: "llamar", english: "to call", german: "anrufen" },
    { spanish: "volver", english: "to return", german: "zurückkehren" },
    { spanish: "empezar", english: "to begin", german: "beginnen" },
    { spanish: "necesitar", english: "to need", german: "brauchen" },
    { spanish: "salir", english: "to leave", german: "weggehen" },
    { spanish: "trabajar", english: "to work", german: "arbeiten" },
    { spanish: "vivir", english: "to live", german: "leben" },
    { spanish: "morir", english: "to die", german: "sterben" },
    { spanish: "nacer", english: "to be born", german: "geboren werden" },
    { spanish: "comer", english: "to eat", german: "essen" },
    { spanish: "beber", english: "to drink", german: "trinken" },
    { spanish: "dormir", english: "to sleep", german: "schlafen" },
    { spanish: "caminar", english: "to walk", german: "gehen" },
    { spanish: "correr", english: "to run", german: "laufen" },
    { spanish: "leer", english: "to read", german: "lesen" },
    { spanish: "escribir", english: "to write", german: "schreiben" },
    { spanish: "estudiar", english: "to study", german: "studieren" },
    { spanish: "aprender", english: "to learn", german: "lernen" },
    { spanish: "enseñar", english: "to teach", german: "lehren" },
    { spanish: "comprar", english: "to buy", german: "kaufen" },
    { spanish: "vender", english: "to sell", german: "verkaufen" },
    { spanish: "abrir", english: "to open", german: "öffnen" },
    { spanish: "cerrar", english: "to close", german: "schließen" },
    { spanish: "entrar", english: "to enter", german: "eintreten" },
    { spanish: "subir", english: "to go up", german: "hinaufgehen" },
    { spanish: "bajar", english: "to go down", german: "hinuntergehen" },
    // Body parts
    { spanish: "cuerpo", english: "body", german: "Körper" },
    { spanish: "cara", english: "face", german: "Gesicht" },
    { spanish: "ojo", english: "eye", german: "Auge" },
    { spanish: "boca", english: "mouth", german: "Mund" },
    { spanish: "nariz", english: "nose", german: "Nase" },
    { spanish: "oreja", english: "ear", german: "Ohr" },
    { spanish: "pelo", english: "hair", german: "Haar" },
    { spanish: "cuello", english: "neck", german: "Hals" },
    { spanish: "brazo", english: "arm", german: "Arm" },
    { spanish: "pierna", english: "leg", german: "Bein" },
    { spanish: "pie", english: "foot", german: "Fuß" },
    { spanish: "dedo", english: "finger", german: "Finger" },
    { spanish: "corazón", english: "heart", german: "Herz" },
    { spanish: "espalda", english: "back", german: "Rücken" },
    { spanish: "estómago", english: "stomach", german: "Magen" },
    // Colors
    { spanish: "color", english: "color", german: "Farbe" },
    { spanish: "blanco", english: "white", german: "weiß" },
    { spanish: "negro", english: "black", german: "schwarz" },
    { spanish: "rojo", english: "red", german: "rot" },
    { spanish: "azul", english: "blue", german: "blau" },
    { spanish: "verde", english: "green", german: "grün" },
    { spanish: "amarillo", english: "yellow", german: "gelb" },
    { spanish: "rosa", english: "pink", german: "rosa" },
    { spanish: "gris", english: "gray", german: "grau" },
    { spanish: "marrón", english: "brown", german: "braun" },
    { spanish: "violeta", english: "purple", german: "lila" },
    // Numbers
    { spanish: "uno", english: "one", german: "eins" },
    { spanish: "dos", english: "two", german: "zwei" },
    { spanish: "tres", english: "three", german: "drei" },
    { spanish: "cuatro", english: "four", german: "vier" },
    { spanish: "cinco", english: "five", german: "fünf" },
    { spanish: "seis", english: "six", german: "sechs" },
    { spanish: "siete", english: "seven", german: "sieben" },
    { spanish: "ocho", english: "eight", german: "acht" },
    { spanish: "nueve", english: "nine", german: "neun" },
    { spanish: "diez", english: "ten", german: "zehn" },
    { spanish: "veinte", english: "twenty", german: "zwanzig" },
    { spanish: "treinta", english: "thirty", german: "dreißig" },
    { spanish: "cien", english: "hundred", german: "hundert" },
    { spanish: "mil", english: "thousand", german: "tausend" },
    // Time and dates
    { spanish: "hoy", english: "today", german: "heute" },
    { spanish: "ayer", english: "yesterday", german: "gestern" },
    { spanish: "mañana", english: "tomorrow", german: "morgen" },
    { spanish: "semana", english: "week", german: "Woche" },
    { spanish: "mes", english: "month", german: "Monat" },
    { spanish: "lunes", english: "Monday", german: "Montag" },
    { spanish: "martes", english: "Tuesday", german: "Dienstag" },
    { spanish: "miércoles", english: "Wednesday", german: "Mittwoch" },
    { spanish: "jueves", english: "Thursday", german: "Donnerstag" },
    { spanish: "viernes", english: "Friday", german: "Freitag" },
    { spanish: "sábado", english: "Saturday", german: "Samstag" },
    { spanish: "domingo", english: "Sunday", german: "Sonntag" },
    { spanish: "enero", english: "January", german: "Januar" },
    { spanish: "febrero", english: "February", german: "Februar" },
    { spanish: "marzo", english: "March", german: "März" },
    { spanish: "abril", english: "April", german: "April" },
    { spanish: "mayo", english: "May", german: "Mai" },
    { spanish: "junio", english: "June", german: "Juni" },
    { spanish: "julio", english: "July", german: "Juli" },
    { spanish: "agosto", english: "August", german: "August" },
    { spanish: "septiembre", english: "September", german: "September" },
    { spanish: "octubre", english: "October", german: "Oktober" },
    { spanish: "noviembre", english: "November", german: "November" },
    { spanish: "diciembre", english: "December", german: "Dezember" },
    // Common greetings and phrases
    { spanish: "hola", english: "hello", german: "hallo" },
    { spanish: "adiós", english: "goodbye", german: "auf Wiedersehen" },
    { spanish: "gracias", english: "thank you", german: "danke" },
    { spanish: "por favor", english: "please", german: "bitte" },
    { spanish: "perdón", english: "excuse me", german: "entschuldigung" },
    { spanish: "lo siento", english: "I'm sorry", german: "es tut mir leid" },
    { spanish: "sí", english: "yes", german: "ja" },
    { spanish: "disculpe", english: "excuse me", german: "entschuldigen Sie" },
    { spanish: "de nada", english: "you're welcome", german: "gern geschehen" },
    { spanish: "buenos días", english: "good morning", german: "guten Morgen" },
    { spanish: "buenas tardes", english: "good afternoon", german: "guten Tag" },
    { spanish: "buenas noches", english: "good evening", german: "guten Abend" },
    { spanish: "¿cómo está?", english: "how are you?", german: "wie geht es Ihnen?" },
    { spanish: "¿cómo estás?", english: "how are you?", german: "wie geht es dir?" },
    { spanish: "bien", english: "well/good", german: "gut" },
    { spanish: "mal", english: "bad", german: "schlecht" },
    { spanish: "así así", english: "so-so", german: "so lala" },
    { spanish: "me llamo", english: "my name is", german: "ich heiße" },
    { spanish: "¿cómo te llamas?", english: "what's your name?", german: "wie heißt du?" },
    { spanish: "mucho gusto", english: "nice to meet you", german: "freut mich" },
    { spanish: "encantado", english: "pleased to meet you", german: "erfreut" },
    { spanish: "¿de dónde eres?", english: "where are you from?", german: "woher kommst du?" },
    { spanish: "soy de", english: "I'm from", german: "ich komme aus" },
    { spanish: "¿cuántos años tienes?", english: "how old are you?", german: "wie alt bist du?" },
    { spanish: "tengo", english: "I have", german: "ich habe" },
    { spanish: "años", english: "years old", german: "Jahre alt" }
];

// Common Spanish words for API expansion (used in app.js for dynamic loading)
const commonSpanishWords = [
    "gato", "perro", "sol", "luna", "libro", "mesa", "silla", "ventana", "puerta", "coche",
    "ciudad", "país", "mundo", "vida", "amor", "feliz", "triste", "grande", "pequeño", "nuevo",
    "viejo", "bueno", "malo", "rápido", "lento", "alto", "bajo", "fuerte", "débil", "caliente",
    "frío", "rojo", "azul", "verde", "amarillo", "negro", "blanco", "uno", "dos", "tres",
    "cuatro", "cinco", "seis", "siete", "ocho", "nueve", "diez", "comer", "beber", "dormir",
    "caminar", "correr", "hablar", "escuchar", "ver", "leer", "escribir", "estudiar", "trabajar", "jugar",
    "música", "película", "televisión", "radio", "teléfono", "ordenador", "internet", "correo", "carta", "regalo",
    "fiesta", "celebración", "cumpleaños", "navidad", "año", "mes", "semana", "día", "hora", "minuto",
    "mañana", "tarde", "noche", "hoy", "ayer", "mañana", "primavera", "verano", "otoño", "invierno",
    "lluvia", "nieve", "viento", "calor", "frío", "nube", "estrella", "montaña", "río", "mar",
    "playa", "bosque", "árbol", "flor", "hierba", "animal", "pájaro", "pez", "caballo", "vaca"
];